# Generated by Django 2.2.1 on 2019-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='desc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
