# Generated by Django 2.2.1 on 2019-07-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190705_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='desc',
            field=models.CharField(blank=True, db_column='描述', max_length=20, null=True),
        ),
    ]
