# Generated by Django 2.2.1 on 2019-07-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_application_host'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temp',
            table='temptable',
        ),
    ]
