# Generated by Django 2.2.1 on 2019-07-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190705_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={'ordering': ['title', '-desc'], 'verbose_name': 'Temp表', 'verbose_name_plural': 'Temp表'},
        ),
        migrations.AlterField(
            model_name='temp',
            name='desc',
            field=models.CharField(blank=True, db_column='描述', help_text='描述', max_length=20, null=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Area')),
            ],
        ),
    ]
