# Generated by Django 2.2.1 on 2019-07-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_pollsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsuser',
            name='telepone',
            field=models.CharField(default='110', max_length=11),
        ),
    ]
