# Generated by Django 2.2.1 on 2019-07-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_auto_20190704_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='type',
            field=models.CharField(choices=[('man', '男'), ('women', '女')], default='man', max_length=5),
        ),
    ]
