# Generated by Django 2.2.1 on 2019-07-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0007_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='doc',
            field=models.FileField(default='', upload_to='doc'),
        ),
    ]
